variable "service_name" {}
variable "feature_name" {}
variable "owner_email" {}
variable "tech_owner_email" {}
variable "environment" {}
variable "squad" {}
variable "finops" {}
variable "repo_name" {}
variable "pipeline" {}
variable "tier" {}
variable "sigla" {}
variable "sn" {}
variable "account_id" {}