apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "topology.kubernetes.io/zone"
                  operator: "In"
                  values: ["us-east-1a"]
                - key: "karpenter.sh/capacity-type"
                  operator: "In"
                  values: ["on-demand"]
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: inflate
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  recommenders:
    - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: inflate
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inflate
  # namespace: default
spec:
  scaleTargetRef:
    name: inflate
  triggers:
  - type: cpu
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "60"
  - type: memory
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "50"
